name: lint-and-deploy
on: [push]

env:
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

jobs:
  lintAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: set up git
        run: |
          git config --global user.email ${GITHUB_ACTOR}@gmail.com
          git config --global user.name ${GITHUB_ACTOR}
      - name: delete release branch
        run: |
          git fetch --prune
          git branch -r
          git push -d origin release
          git branch -d release
      - name: create release branch
        run: |
          git branch release
          git checkout release
          git push origin release -f --set-upstream
